defaults: &defaults
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  pool: 14
  reaping_frequency: 10

development:
  <<: *defaults
  database: awign_dev

test: &test
  <<: *defaults
  database: awign_test


production:
  <<: *defaults
  database: awign_production
